---
title: "Untitled"
author: "Jirka Lewandowski <jirka.lewandowski@wzb.eu>"
date: "14 10 2016"
output: ioslides_presentation
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r message=FALSE}
library(dplyr)
library(readr)
library(DT)
library(ggplot2)
library(networkD3)

source("js.R")
party_fingerprints <- read_csv("party_fingerprints.csv")
party_differences <- read_csv("party_differences.csv")
#%>%
  #group_by(words) %>%
  #summarise(js_all = multi_js(list(AfD, ChrDem, Greens, Left, Liberals, SocDem))) %>%
  #ungroup() %>%
  #arrange(desc(js_all)) %>%
  #head(n = 200) -> party_differences
```

## Idea

## Results

```{r}
shinyApp(ui = shinyUI(fluidPage(
  fluidRow(column(width = 4, wellPanel(style = "overflow-y:scroll; overflow-x:hidden; max-height: 600px", dataTableOutput("top_words"))),
           column(width = 8,
                  wellPanel(style = "overflow-y:hidden; max-height: 600px",
                            sankeyNetworkOutput("plot"))))
)),
         server = shinyServer(function(input, output, session) {
           
           output$top_words <- DT::renderDataTable(DT::datatable(transmute(party_differences,
                                                                           word = words),
                                                                           # distinctiveness = round(js_all, digits = 3)),
                                                                 selection = "single",
                                                                 autoHideNavigation = TRUE,
                                                                 options = list(lengthChange = FALSE,
                                                                                searching = FALSE,
                                                                                pageLength = 1000)))

           selected_word <- reactive(input$top_words_rows_selected %>%
                                       last() %>%
                                       { party_differences[., "words"] } %>%
                                       unlist())
           
           
           top_words <- reactive(party_fingerprints %>%
             filter(words == selected_word()) %>%
             group_by(partyname) %>%
             mutate(context_characteristic = p_context*entropy(p_context)) %>%
             top_n(n = 4, wt = context_characteristic) %>%
             mutate(n = row_number()) %>%
             top_n(n = 4, wt = n) %>%
             ungroup() %>%
             select(partyname,
                    context_word = context_words,
                    conditional_probability = context_characteristic))
           
           output$associations <- renderDataTable(top_words())
           
           output$plot <- renderSankeyNetwork({
             Nodes <- top_words() %>%
                        select(partyname, context_word) %>%
                        unlist() %>%
                        unique() %>%
                        { data_frame(name = .) } %>%
                        mutate(ID = row_number() - 1) %>%
                        left_join(c("Greens" = "green",
                                    "AfD" = "blue",
                                    "Left" = "#ff66bb",
                                    "SocDem" = "red",
                                    "ChrDem" = "black",
                                    "Liberals" = "yellow") %>%
                                    data_frame(color = ., name = names(.))) %>%
                        mutate(color = ifelse(is.na(color), "#666666", color))
             NodeList <- as.list(Nodes$ID) %>% set_names(Nodes$name)
             sankeyNetwork(Links = top_words() %>%
                             mutate(partyname = unlist(NodeList[partyname]),
                                    context_word = unlist(NodeList[context_word])),
                           Nodes = Nodes,
                           NodeID = "name",
                           NodeGroup = "color",
                           Source = "partyname",
                           colourScale = JS("String"), ## bloody hack
                           Target = "context_word",
                           Value = "conditional_probability",
                           fontSize = 20, nodeWidth = 30, fontFamily = "sans-serif")
             })
           
           # output$plot <- renderPlot(ggplot(top_words(),
           #                                  aes(x = context_word, y = conditional_probability, fill = partyname)) + 
           #                             geom_bar(stat = "identity") + 
           #                             theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
           #                             scale_fill_manual(values = c("Greens" = "green", "AfD" = "blue", "Left" = "#ff66bb", "SocDem" = "red", "ChrDem" = "black", "Liberals" = "yellow")))
         }))
```

